# Generated by Django 4.2.7 on 2023-11-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentid', models.CharField(max_length=10)),
                ('appointmentdate', models.DateField(auto_now_add=True)),
                ('Tokenno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bloodgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Lab Technician', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Receptionist', 'Receptionist')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_joining', models.DateField()),
                ('education', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobileno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('bloodGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.bloodgroup')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibackendapp.department')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibackendapp.specialization')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='apibackendapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField()),
                ('billamount', models.IntegerField()),
                ('billdate', models.DateTimeField(auto_now_add=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specializationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.specialization'),
        ),
    ]
