# Generated by Django 4.2.7 on 2023-11-14 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apibackendapp', '0002_alter_doctor_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestManagement',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('time_of_consumption', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bill',
            new_name='ReceptionBill',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentdate',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentid',
            new_name='appointment_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctorid',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patientid',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='specializationid',
            new_name='specialization_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Tokenno',
            new_name='token_no',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='bloodGroup',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mobileno',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patientId',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='receptionbill',
            old_name='appointmentid',
            new_name='appointment_id',
        ),
        migrations.RenameField(
            model_name='receptionbill',
            old_name='billamount',
            new_name='bill_amount',
        ),
        migrations.RenameField(
            model_name='receptionbill',
            old_name='billdate',
            new_name='bill_date',
        ),
        migrations.RenameField(
            model_name='receptionbill',
            old_name='billno',
            new_name='bill_no',
        ),
        migrations.RenameField(
            model_name='receptionbill',
            old_name='patientid',
            new_name='patient_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultatiionfees',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.CreateModel(
            name='TestPrescriptionTests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.labtestmanagement')),
                ('test_prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.testprescription')),
            ],
        ),
        migrations.AddField(
            model_name='testprescription',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment'),
        ),
        migrations.AddField(
            model_name='testprescription',
            name='choose_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.labtestmanagement'),
        ),
        migrations.AddField(
            model_name='testprescription',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor'),
        ),
        migrations.AddField(
            model_name='testprescription',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient'),
        ),
        migrations.CreateModel(
            name='MedicinePrescriptionMedicines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicinedetails')),
                ('medicine_prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicineprescription')),
            ],
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicinedetails'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient'),
        ),
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_visit', models.DateField()),
                ('observation_details', models.TextField()),
                ('diagnosis_details', models.TextField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBill',
            fields=[
                ('bill_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('paying_status', models.BooleanField(default=False)),
                ('medicine_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicineprescription')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Pending', max_length=20, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=5)),
                ('low_range', models.FloatField()),
                ('high_range', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
    ]
