# Generated by Django 4.2.7 on 2023-11-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0003_labtestmanagement_medicinedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultatiionfees',
        ),
    ]
