# Generated by Django 4.2.7 on 2023-11-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0004_remove_doctor_consultatiionfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultationfees',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
