# Generated by Django 4.2.7 on 2023-11-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0005_doctor_consultationfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineprescription',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='testprescriptiontests',
            name='test_id',
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine_id',
            field=models.ManyToManyField(to='apibackendapp.medicinedetails'),
        ),
        migrations.AddField(
            model_name='testprescriptiontests',
            name='test_id',
            field=models.ManyToManyField(to='apibackendapp.labtestmanagement'),
        ),
    ]
