# Generated by Django 4.2.7 on 2023-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0006_remove_medicineprescription_medicine_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprescriptiontests',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='testprescriptiontests',
            name='test_prescription_id',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='test_id',
            field=models.ManyToManyField(blank=True, to='apibackendapp.labtestmanagement'),
        ),
        migrations.AlterField(
            model_name='medicinedetails',
            name='medicine_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicineprescription',
            name='medicine_id',
            field=models.ManyToManyField(blank=True, to='apibackendapp.medicinedetails'),
        ),
        migrations.DeleteModel(
            name='TestPrescription',
        ),
        migrations.DeleteModel(
            name='TestPrescriptionTests',
        ),
    ]
