# Generated by Django 4.2.7 on 2023-11-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0007_remove_testprescriptiontests_test_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestmanagement',
            name='test_name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
