# Generated by Django 4.2.7 on 2023-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0010_alter_medicinebill_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
