# Generated by Django 4.2.7 on 2023-11-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0011_alter_patient_blood_group_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
