# Generated by Django 4.2.7 on 2023-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0012_alter_appointment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionbill',
            name='token_no',
            field=models.IntegerField(default=None),
        ),
    ]
