# Generated by Django 4.2.7 on 2023-11-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0014_receptionbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionbill',
            name='doctor_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor'),
        ),
    ]
