# Generated by Django 4.2.7 on 2023-11-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0015_receptionbill_doctor_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receptionbill',
            table='apibackendapp_receptionbill',
        ),
    ]
