# Generated by Django 4.2.7 on 2023-11-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0020_alter_receptionbill_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receptionbill',
            table=None,
        ),
    ]
