# Generated by Django 4.2.7 on 2023-11-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0021_alter_receptionbill_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receptionbill',
            table='apibackendapp_receptionbill',
        ),
    ]
