# Generated by Django 4.2.7 on 2023-11-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0022_alter_receptionbill_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receptionbill',
            table='receptionbill',
        ),
    ]
