# Generated by Django 4.2.7 on 2023-11-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0023_alter_receptionbill_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionbill',
            name='status',
            field=models.CharField(default='paid', max_length=4),
        ),
    ]
