# Generated by Django 4.2.7 on 2023-11-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0024_alter_receptionbill_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receptionbill',
            table='your_table_name',
        ),
    ]
