# Generated by Django 4.2.7 on 2023-11-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0025_alter_receptionbill_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineprescription',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='test_id',
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.medicinedetails'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='test_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.labtestmanagement'),
        ),
    ]
