# Generated by Django 4.2.7 on 2023-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0026_remove_medicineprescription_medicine_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineprescription',
            name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='medicineprescription',
            name='test_id',
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='medicine_id',
            field=models.ManyToManyField(blank=True, to='apibackendapp.medicinedetails'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='test_id',
            field=models.ManyToManyField(blank=True, to='apibackendapp.labtestmanagement'),
        ),
    ]
